import { existsSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { UNSCOPED_ENVIRONMENT } from "../git_env";
import { OrlyError } from "../model";
import { HOOK_INVOCATION_ENV, HOOK_INVOCATION_VALUE } from "../telemetry";
import type { RepoConfig } from "../config";
import type { PlannedFile } from "./plan";

export const HOOKS_DIRECTORY = ".orly/hooks";
const HOOKS_PATH_KEY = "core.hooksPath";
const GIT_CONFIG = "config";
const PIPE_OUTPUT = "pipe";
const HOOK_GATES = [["pre-commit", "work"], ["pre-push", "verify"]] as const;
const EXECUTABLE_BITS = 0o111;

export function plannedHooks(version: string): PlannedFile[] {
  if (!/^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/.test(version)) throw new OrlyError("hook package version must be a release version");
  return HOOK_GATES.map(([name, gate]) => ({ target: `${HOOKS_DIRECTORY}/${name}`, content: Buffer.from(hookScript(gate, version)), mode: "0755" }));
}

export function checkHooks(root: string, config: RepoConfig, force: boolean): void {
  const existing = hooksPath(root);
  if (existing === HOOKS_DIRECTORY || force) return;
  const previous = existing ?? git(root, ["rev-parse", "--git-path", "hooks"]).stdout.toString().trim();
  const directory = resolve(root, previous);
  const managed = existing === ".githooks" && HOOK_GATES.every(([name]) => config.managed.includes(`${existing}/${name}`));
  const ownerHook = existsSync(directory) && readdirSync(directory).some((name) => {
    if (name.endsWith(".sample") || (managed && HOOK_GATES.some(([hook]) => hook === name))) return false;
    const stat = statSync(join(directory, name));
    return stat.isFile() && (stat.mode & EXECUTABLE_BITS) !== 0;
  });
  if ((!existing || managed) && !ownerHook) return;
  throw new OrlyError(`${HOOKS_PATH_KEY} uses '${previous}' with repository hooks; use --no-hooks to preserve repository hooks, or explicitly --force to retarget`);
}

export function hooksPath(root: string): string | null {
  const result = git(root, [GIT_CONFIG, "--get", HOOKS_PATH_KEY]);
  if (result.exitCode === 1) return null;
  if (result.exitCode !== 0) throw new OrlyError(`cannot read ${HOOKS_PATH_KEY}: ${result.stderr.toString().trim()}`);
  return result.stdout.toString().trim();
}

export function configureHooks(root: string): void {
  const result = git(root, [GIT_CONFIG, HOOKS_PATH_KEY, HOOKS_DIRECTORY]);
  if (result.exitCode !== 0) throw new OrlyError(`cannot configure ${HOOKS_PATH_KEY}: ${result.stderr.toString().trim()}`);
}

function git(root: string, args: string[]) {
  return Bun.spawnSync(["git", "-C", root, ...args], { env: UNSCOPED_ENVIRONMENT, stdout: PIPE_OUTPUT, stderr: PIPE_OUTPUT });
}

function hookScript(gate: string, version: string): string {
  return [
    "#!/usr/bin/env bash",
    "# Generated by orly. Re-run the pinned bunx update to refresh.",
    "set -euo pipefail",
    "unset GIT_DIR GIT_INDEX_FILE GIT_WORK_TREE GIT_COMMON_DIR GIT_PREFIX \\",
    "      GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES",
    `export ${HOOK_INVOCATION_ENV}=${HOOK_INVOCATION_VALUE}`,
    `exec bunx --bun @agentsfleet/orly@${version} gate ${gate}`,
    "",
  ].join("\n");
}
