import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { CONFIG_PATH, contentDigest, parseConfig, readConfig, sameDigest, type RepoConfig } from "../config";
import { assertWritableInside, OrlyError } from "../model";
import { HOOK_INVOCATION_ENV, HOOK_INVOCATION_VALUE } from "../telemetry";
import type { FileDelete } from "./transaction";

export const PREVIOUS_CONFIG = ".oracle/orly.json";
const TEXT_ENCODING = "utf8";

// Only installation may read the old location. Gates require the current one.
export async function readInstallConfig(root: string): Promise<RepoConfig | undefined> {
  const current = await readConfig(root);
  if (current) return current;
  assertWritableInside(root, PREVIOUS_CONFIG, "migration configuration");
  const path = join(root, PREVIOUS_CONFIG);
  if (!existsSync(path)) return undefined;
  return parseConfig(JSON.parse(readFileSync(path, TEXT_ENCODING)));
}

export function migrationDeletes(root: string, config: RepoConfig, destinations: Set<string>): FileDelete[] {
  const deletes: FileDelete[] = [];
  for (const path of config.managed) {
    if (destinations.has(path) || path === "AGENTS.md") continue;
    assertWritableInside(root, path, "migration source");
    if (!existsSync(join(root, path))) continue;
    const current = contentDigest(readFileSync(join(root, path)));
    const recorded = config.digests[path] ?? previousHookDigest(root, path);
    if (!recorded || !sameDigest(recorded, current)) throw new OrlyError(`migration conflict: ${path} lacks matching recorded ownership; preserve or reconcile it before updating`);
    deletes.push({ path, before: current });
  }
  if (!existsSync(join(root, CONFIG_PATH)) && existsSync(join(root, PREVIOUS_CONFIG))) {
    deletes.push({ path: PREVIOUS_CONFIG, before: contentDigest(readFileSync(join(root, PREVIOUS_CONFIG))) });
  }
  return deletes;
}

function previousHookDigest(root: string, path: string): string | undefined {
  const gate = path === ".githooks/pre-commit" ? "work" : path === ".githooks/pre-push" ? "verify" : undefined;
  if (!gate) return undefined;
  const content = readFileSync(join(root, path));
  return content.toString(TEXT_ENCODING) === previousHookScript(gate) ? contentDigest(content) : undefined;
}

function previousHookScript(gate: string): string {
  return [
    "#!/usr/bin/env bash",
    "# Generated by orly. Re-run `orly init` to refresh.",
    "set -euo pipefail",
    "",
    "# git exports these to every hook; inherited by a spawned git they pin it to",
    "# the hook's repository instead of the one being judged.",
    "unset GIT_DIR GIT_INDEX_FILE GIT_WORK_TREE GIT_COMMON_DIR GIT_PREFIX \\",
    "      GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES",
    "",
    'if ! command -v orly >/dev/null 2>&1; then',
    "    printf '%s\\n' 'orly: not on PATH — install it with `bun add -g @agentsfleet/orly`' >&2",
    "    exit 1",
    "fi",
    "",
    `export ${HOOK_INVOCATION_ENV}=${HOOK_INVOCATION_VALUE}`,
    `exec orly gate ${gate}`,
    "",
  ].join("\n");
}
