[package]
name = "orly-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
schemars = { workspace = true }
sha2 = { workspace = true }
digest-io = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
cap-std = { workspace = true }
cap-fs-ext = { workspace = true }
cap-tempfile = { workspace = true }
same-file = { workspace = true }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
