pub const ENGINE_VERSION: &str = env!("CARGO_PKG_VERSION");
pub const CONFIG_PATH: &str = ".orly/orly.json";
pub const ORLY_AGENTS_FILENAME: &str = ".orly/AGENTS.md";
pub const AGENTS_FILENAME: &str = "AGENTS.md";
pub const REGISTRY_PATH: &str = "registry.json";
pub const UNIVERSAL_PACK: &str = "universal.authoring";
pub const OLD_CONFIG_PATH: &str = ".oracle/orly.json";
pub const OLD_AGENTS_FILENAME: &str = "AGENTS.orly.md";
pub const PRIOR_ENGINE_VERSION: &str = "0.10.14";
pub const PRIOR_HOOKS_DIRECTORY: &str = ".githooks";
pub const PRIOR_PRE_COMMIT: &str = ".githooks/pre-commit";
pub const PRIOR_PRE_PUSH: &str = ".githooks/pre-push";
pub const ORLY_PREFIX: &str = ".orly/";
pub const GENERATED_BANNER: &str = "> **Generated by `orly`.**";
pub const GIT_COMMAND: &str = "git";
pub const HOOKS_DIRECTORY: &str = ".orly/hooks";
pub const HOOKS_PATH_KEY: &str = "core.hooksPath";
pub const PRE_COMMIT: &str = "pre-commit";
pub const PRE_PUSH: &str = "pre-push";
const ENGINE_BINARY_PREFIX: &str = ".orly/bin/orly-";
const HOOK_BINARY_PREFIX: &str = "../bin/orly-";
#[cfg(windows)]
const EXECUTABLE_SUFFIX: &str = ".exe";
#[cfg(unix)]
pub const ENGINE_BINARY: &str = constcat::concat!(ENGINE_BINARY_PREFIX, ENGINE_VERSION);
#[cfg(windows)]
pub const ENGINE_BINARY: &str =
    constcat::concat!(ENGINE_BINARY_PREFIX, ENGINE_VERSION, EXECUTABLE_SUFFIX);
#[cfg(unix)]
pub const HOOK_BINARY_LINK: &str = constcat::concat!(HOOK_BINARY_PREFIX, ENGINE_VERSION);
#[cfg(windows)]
pub const HOOK_BINARY_LINK: &str =
    constcat::concat!(HOOK_BINARY_PREFIX, ENGINE_VERSION, EXECUTABLE_SUFFIX);
pub const MANIFEST_PATH: &str = "orly/installation.json";
pub const LOCK_PATH: &str = "orly/installation.lock";
pub const CONFIG_SCHEMA: u32 = 2;
pub use orly_decision::WIRE_VERSION;
pub const MAX_OUTPUT_BYTES: usize = 4 * 1024 * 1024;
pub const DEFAULT_DEADLINE_SECONDS: u64 = 300;
pub const MAX_DEADLINE_SECONDS: u64 = 3600;
pub const MAX_PLAN_NODES: usize = 1024;
pub const MAX_COMMAND_PARALLELISM: usize = 16;
pub const MAX_SOURCE_BYTES: usize = 64 * 1024 * 1024;
pub const MAX_SNAPSHOT_BYTES: usize = 512 * 1024 * 1024;
pub const UNAVAILABLE_CODE: &str = "feature_unavailable";
pub use orly_fs::constants::MAX_BINARY_BYTES;
