import { describe, expect, test } from "bun:test";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const COMMAND = resolve(ROOT, "bin/orly");

describe("orly command", () => {
  test("uses the concise public command surface", () => {
    const result = Bun.spawnSync([COMMAND, "--help"], { cwd: ROOT, stdout: "pipe", stderr: "pipe" });
    const output = result.stdout.toString();

    expect(result.exitCode).toBe(0);
    expect(output).toContain("orly gate");
    expect(output).toContain("orly override <CRITERION> --reason <REASON>");
    expect(output).not.toContain("orly adopt");
    expect(output).not.toContain("oracle-rules");
  });

  test("telemetry_help_names_tiers_storage_and_privacy", () => {
    const result = Bun.spawnSync([COMMAND, "--help"], { cwd: ROOT, stdout: "pipe", stderr: "pipe" });
    const output = result.stdout.toString();

    expect(output).toContain("off by default");
    expect(output).toContain("anonymous");
    expect(output).toContain("~/.config/agentsfleet/orly/.orly.json");
    expect(output).toContain("AGENTSFLEET_STATE_DIR");
    expect(output).toContain("ORLY_TELEMETRY_OFF=1");
    expect(output).toContain("packaged Orly skill");
    expect(output).toContain("never collects source, paths, repositories, branches, arguments, prompts");
  });

  // Adversarial review found recordOptIn running before the --dry-run branch,
  // so a preview created .oracle/orly.json — and on an installed repository
  // permanently added the pack. A dry run changes nothing, opt-in included.
  test("--dry-run records no pack", () => {
    const repo = mkdtempSync(join(tmpdir(), "orly-dry-"));
    try {
      Bun.spawnSync(["git", "init", "-q", repo], { stdout: "pipe", stderr: "pipe" });
      writeFileSync(join(repo, "m.go"), "package main\n");

      const result = Bun.spawnSync([COMMAND, "init", "--with", "persona.indy", "--dry-run"], { cwd: repo, stdout: "pipe", stderr: "pipe" });

      expect(result.exitCode).toBe(0);
      expect(result.stdout.toString()).toContain("Generated by");
      expect(existsSync(join(repo, ".oracle/orly.json"))).toBe(false);
      expect(existsSync(join(repo, "AGENTS.orly.md"))).toBe(false);
    } finally {
      rmSync(repo, { recursive: true, force: true });
    }
  });

  test("reports the version carried by the package manifest", async () => {
    const result = Bun.spawnSync([COMMAND, "--version"], { cwd: ROOT, stdout: "pipe", stderr: "pipe" });
    const manifest = (await Bun.file(resolve(ROOT, "package.json")).json()) as { version: string };

    expect(result.exitCode).toBe(0);
    expect(result.stdout.toString().trim()).toBe(manifest.version);
  });

  // `validate` is gone: verifyRenders calls model.validate() before its own
  // checks, so the verb was a strict subset of `verify` with a second name.
  test("verify validates the registry on its way to the render checks", () => {
    const result = Bun.spawnSync([COMMAND, "verify"], { cwd: ROOT, stdout: "pipe", stderr: "pipe" });

    expect(result.exitCode).toBe(0);
    expect(result.stdout.toString()).toContain("render.local.idempotent");
  });

  test("validate is not a verb", () => {
    const result = Bun.spawnSync([COMMAND, "validate"], { cwd: ROOT, stdout: "pipe", stderr: "pipe" });

    expect(result.exitCode).toBe(1);
    expect(result.stderr.toString()).toContain("unknown command: validate");
  });

  test("verify needs no --all, because there was never a not-all", () => {
    const result = Bun.spawnSync([COMMAND, "verify"], { cwd: ROOT, stdout: "pipe", stderr: "pipe" });

    expect(result.exitCode).toBe(0);
  });

  test("telemetry_failure_never_changes_command_result", () => {
    const blockedRoot = join(mkdtempSync(join(tmpdir(), "orly-telemetry-blocked-")), "state-file");
    writeFileSync(blockedRoot, "not a directory\n");
    const enabled = { ...process.env, AGENTSFLEET_STATE_DIR: blockedRoot, ORLY_TELEMETRY: "anonymous" };
    const off = { ...enabled, ORLY_TELEMETRY_OFF: "1" };
    try {
      const successWithFailure = Bun.spawnSync([COMMAND, "doctor"], { cwd: ROOT, env: enabled, stdout: "pipe", stderr: "pipe" });
      const successWithOff = Bun.spawnSync([COMMAND, "doctor"], { cwd: ROOT, env: off, stdout: "pipe", stderr: "pipe" });
      const errorWithFailure = Bun.spawnSync([COMMAND, "gate", "nope"], { cwd: ROOT, env: enabled, stdout: "pipe", stderr: "pipe" });
      const errorWithOff = Bun.spawnSync([COMMAND, "gate", "nope"], { cwd: ROOT, env: off, stdout: "pipe", stderr: "pipe" });

      expect(successWithFailure.exitCode).toBe(successWithOff.exitCode);
      expect(successWithFailure.stdout.toString()).toBe(successWithOff.stdout.toString());
      expect(errorWithFailure.exitCode).toBe(errorWithOff.exitCode);
      expect(errorWithFailure.stderr.toString()).toBe(errorWithOff.stderr.toString());
    } finally {
      rmSync(dirname(blockedRoot), { recursive: true, force: true });
    }
  });

  test("gate_command_records_its_selected_gate_and_failed_criterion", async () => {
    const root = mkdtempSync(join(tmpdir(), "orly-telemetry-command-"));
    const repo = join(root, "repo");
    const stateRoot = join(root, "state");
    Bun.spawnSync(["git", "init", "-q", repo]);
    writeFileSync(join(repo, "README.md"), "fixture\n");
    Bun.spawnSync(["git", "-C", repo, "add", "README.md"]);
    Bun.spawnSync(["git", "-C", repo, "-c", "user.name=Orly Test", "-c", "user.email=orly@example.invalid", "commit", "-q", "-m", "test: seed"]);
    Bun.spawnSync(["git", "-C", repo, "checkout", "-q", "-b", "feat/telemetry"]);
    const env = {
      ...process.env,
      AGENTSFLEET_STATE_DIR: stateRoot,
      ORLY_TELEMETRY: "anonymous",
      ORLY_TELEMETRY_OFF: "0",
      ORLY_POSTHOG_HOST: "http://127.0.0.1:1",
    };
    try {
      const result = Bun.spawnSync([COMMAND, "gate", "pr"], { cwd: repo, env, stdout: "pipe", stderr: "pipe" });
      expect(result.exitCode).toBe(1);
      const failedCriterion = result.stdout.toString().match(/🔴 ([^:]+):/)?.[1];
      expect(failedCriterion).toBeDefined();

      const spool = join(stateRoot, "orly/analytics/orly-usage.jsonl");
      for (let attempt = 0; attempt < 20 && !existsSync(spool); attempt += 1) await Bun.sleep(10);
      const event = JSON.parse(readFileSync(spool, "utf8"));
      expect(event).toMatchObject({ command: "gate", gate: "pr", outcome: "error", failed_criterion: failedCriterion });
      expect(event.duration_ms).toBeGreaterThanOrEqual(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("skill_event_accepts_only_packaged_skills", () => {
    const env = { ...process.env, ORLY_TELEMETRY_OFF: "1", ORLY_INVOCATION: "skill" };
    const packagedSkills = ["orly-babysit-prs", "orly-spec-new", "orly-write-integration-test", "orly-write-unit-test"];
    for (const skill of packagedSkills) {
      const accepted = Bun.spawnSync([COMMAND, "skill-event", skill], { cwd: ROOT, env, stdout: "pipe", stderr: "pipe" });
      expect(accepted.exitCode).toBe(0);
      expect(accepted.stdout.toString()).toBe("");
      expect(readFileSync(join(ROOT, "skills", skill, "SKILL.md"), "utf8")).toContain(`orly skill-event ${skill}`);
    }
    const rejected = Bun.spawnSync([COMMAND, "skill-event", "other-skill"], { cwd: ROOT, env, stdout: "pipe", stderr: "pipe" });

    expect(rejected.exitCode).toBe(1);
    expect(rejected.stderr.toString()).toContain("skill-event requires a packaged Orly skill name");
    expect(Bun.spawnSync([COMMAND, "--help"], { cwd: ROOT, env, stdout: "pipe" }).stdout.toString()).not.toContain("skill-event");
  });
});
