import { afterEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readdirSync, rmSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { cleanupTemporaryDirectories, git, gitOutput, newRepository, ROOT } from "./gates_test_support";
import { install } from "./install";
import { readConfig } from "./config";
import { RulesModel } from "./model";

afterEach(cleanupTemporaryDirectories);


describe("installation loaders and hooks", () => {
  test("an existing AGENTS.md survives byte for byte and orly lands beside it", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    const theirs = "# Our house rules\n\nAlways run `go vet`. Never touch vendor/.\n";
    await Bun.write(join(repo, "AGENTS.md"), theirs);
    await Bun.write(join(repo, "m.go"), "package main\n");

    const result = await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    expect(result.ok).toBe(true);
    expect(existsSync(join(repo, ".orly/AGENTS.md"))).toBe(true);
    const host = await Bun.file(join(repo, "AGENTS.md")).text();
    expect(host).toStartWith(theirs.trimEnd());
    expect(host).toContain(".orly/AGENTS.md");
    // Their file is theirs: orly owns only the block, never the whole file.
    expect((await readConfig(repo))?.managed).not.toContain("AGENTS.md");
  });

  test("the orly pointer block is idempotent across repeated installs", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    await Bun.write(join(repo, "AGENTS.md"), "# Ours\n");
    await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });
    const afterFirst = await Bun.file(join(repo, "AGENTS.md")).text();

    const second = await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    expect(second.ok).toBe(true);
    expect(await Bun.file(join(repo, "AGENTS.md")).text()).toBe(afterFirst);
    expect(afterFirst.split("<!-- orly:begin -->").length - 1).toBe(1);
  });

  // One layout everywhere, so `update` never asks which mode it is in and a
  // repository that starts with no rules still has the file to put them in.
  test("a repository with no AGENTS.md still gets both files", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();

    await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    expect(await Bun.file(join(repo, ".orly/AGENTS.md")).text()).toStartWith("> **Generated by `orly`.**");
    const host = await Bun.file(join(repo, "AGENTS.md")).text();
    expect(host).toContain(".orly/AGENTS.md");
    expect(host).toContain("Write this repository's own rules below");
    expect((await readConfig(repo))?.managed).not.toContain("AGENTS.md");
  });

  // Anything installed before the split holds orly's render under AGENTS.md.
  // That content is generated, so replacing it with the stub loses nothing.
  test("an unrecorded generated banner cannot authorize deleting repository content", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    await Bun.write(join(repo, "AGENTS.md"), "> **Generated by `orly`.**\nold single-file layout\n");

    await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    const host = await Bun.file(join(repo, "AGENTS.md")).text();
    expect(host).toContain("old single-file layout");
    expect(host).toContain(".orly/AGENTS.md");
    expect(await Bun.file(join(repo, ".orly/AGENTS.md")).text()).toStartWith("> **Generated by `orly`.**");
  });

  // Rule pages cite `AGENTS.md` meaning orly's rules — true only where they are
  // authored. In a consumer that citation has to name the file orly wrote.
  test("rule pages cite the file orly actually wrote, not the repository's", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    await Bun.write(join(repo, "src/lib.rs"), "pub fn main() {}\n");

    const result = await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    expect(result.ok).toBe(true);
    const rules = await Bun.file(join(repo, ".orly/docs/DOCUMENTATION_RULES.md")).text();
    const parent = rules.match(/Parent:.*?\]\(([^)]+)\)/)?.[1];
    expect(parent).toBeDefined();
    expect(resolve(repo, ".orly/docs", parent!)).toBe(resolve(repo, ".orly/AGENTS.md"));
  });

  test("update rewrites orly's file and leaves the repository's own alone", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    await Bun.write(join(repo, "AGENTS.md"), "# Ours\n");
    await install(model, { targetRoot: repo, force: true, installHooks: true, orlyVersion: "0.4.0" });
    await Bun.write(join(repo, ".orly/AGENTS.md"), "hand-edited\n");
    const host = await Bun.file(join(repo, "AGENTS.md")).text();

    const second = await install(model, { targetRoot: repo, force: true, installHooks: true, orlyVersion: "0.4.0" });

    expect(second.ok).toBe(true);
    expect(second.written).toContain(".orly/AGENTS.md");
    expect(await Bun.file(join(repo, ".orly/AGENTS.md")).text()).toStartWith("> **Generated by `orly`.**");
    expect(await Bun.file(join(repo, "AGENTS.md")).text()).toBe(host);
  });

  test("a hook orly did not write is refused, not clobbered", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    const theirs = "#!/usr/bin/env bash\necho 'our precious hook'\n";
    await Bun.write(join(repo, ".orly/hooks/pre-commit"), theirs);

    const result = await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    expect(result.ok).toBe(false);
    expect(result.errors.map((error) => error.path)).toContain(".orly/hooks/pre-commit");
    expect(await Bun.file(join(repo, ".orly/hooks/pre-commit")).text()).toBe(theirs);
    // A refusal leaves no footprint: the managed files never landed either.
    expect(existsSync(join(repo, "AGENTS.md"))).toBe(false);
  });

  test("generated_hooks_mark_telemetry_invocation", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    await Bun.write(join(repo, ".orly/hooks/pre-commit"), "#!/usr/bin/env bash\necho 'ours'\n");

    const result = await install(model, { targetRoot: repo, force: true, installHooks: true, orlyVersion: "0.4.0" });

    expect(result.ok).toBe(true);
    expect(await Bun.file(join(repo, ".orly/hooks/pre-commit")).text()).toContain("export ORLY_INVOCATION=hook");
    expect(await Bun.file(join(repo, ".orly/hooks/pre-push")).text()).toContain("export ORLY_INVOCATION=hook");
  });

  test("--no-hooks installs the rules over an existing hook without touching it", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    const theirs = "#!/usr/bin/env bash\necho 'ours'\n";
    await Bun.write(join(repo, ".orly/hooks/pre-commit"), theirs);

    const result = await install(model, { targetRoot: repo, force: false, installHooks: false, orlyVersion: "0.4.0" });

    expect(result.ok).toBe(true);
    expect(await Bun.file(join(repo, ".orly/hooks/pre-commit")).text()).toBe(theirs);
    expect(existsSync(join(repo, "AGENTS.md"))).toBe(true);
  });

  test("refuses to retarget a hooksPath already claimed by something else", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    git(repo, "config", "core.hooksPath", "some-other-tools-hooks");

    const result = await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    expect(result.ok).toBe(false);
    expect(result.errors.some((error) => error.path === "core.hooksPath")).toBe(true);
    expect(gitOutput(repo, "config", "--get", "core.hooksPath")).toBe("some-other-tools-hooks");
    expect(existsSync(join(repo, "AGENTS.md"))).toBe(false);
  });

  test("--no-hooks proceeds even when hooksPath is claimed by something else", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    git(repo, "config", "core.hooksPath", "some-other-tools-hooks");

    const result = await install(model, { targetRoot: repo, force: false, installHooks: false, orlyVersion: "0.4.0" });

    expect(result.ok).toBe(true);
    expect(gitOutput(repo, "config", "--get", "core.hooksPath")).toBe("some-other-tools-hooks");
  });

  test("--force retargets a hooksPath claimed by something else", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    git(repo, "config", "core.hooksPath", "some-other-tools-hooks");

    const result = await install(model, { targetRoot: repo, force: true, installHooks: true, orlyVersion: "0.4.0" });

    expect(result.ok).toBe(true);
    expect(gitOutput(repo, "config", "--get", "core.hooksPath")).toBe(".orly/hooks");
  });

  test("re-running init after it already set hooksPath is not a claim by another tool", async () => {
    const model = await RulesModel.load(ROOT);
    const repo = newRepository();
    await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    const second = await install(model, { targetRoot: repo, force: false, installHooks: true, orlyVersion: "0.4.0" });

    expect(second.ok).toBe(true);
  });

  // Adversarial review, reproduced: a repository the user cloned can commit a
  // symlink at a path init would otherwise write to. mkdirSync/writeFile/
  // rename all follow an existing symlink silently — without this refusal,
  // every managed file materialises through it into wherever the symlink
  // points, outside the repository entirely, with `ok: true` and no warning.
  // Adversarial review found this: every other write was guarded, the pointer
  // host was not, and it is the one write orly aims at a file it does not own.
  // A committed `AGENTS.md -> ../outside/victim` carried the block out of the
  // repository and reported a normal success.
});
