import { existsSync, lstatSync, realpathSync } from "node:fs";
import { join } from "node:path";

import { assertWritableInside, isObject } from "./model";

// How orly's rules reach an agent's context, as opposed to how they reach the
// disk. Installing the file is not delivering it: every runtime decides for
// itself what it loads at session start, and only one of the four this
// repository grades against loads AGENTS.md unprompted. A pointer an agent has
// to notice and follow is a hope; an import a runtime resolves is a mechanism.
// So the rules land beside a small set of loaders, one per runtime that has a
// deterministic way in, and the runtimes with no way in are covered by the
// read-record gate instead.
//
// Every file here belongs to the repository, not to orly — they are the same
// class as the pointer host: written when absent, edited only inside a
// delimited block, never listed in `managed`, and never replaced wholesale
// once someone else has written one.

export const AGENTS_FILENAME = "AGENTS.md";
export const ORLY_AGENTS_FILENAME = "AGENTS.orly.md";
export const GENERATED_BANNER = "> **Generated by `orly`.**";
export const POINTER_HOST_KIND = "pointer host";

const CLAUDE_FILENAME = "CLAUDE.md";
const OPENCODE_FILENAME = "opencode.json";
const OPENCODE_SCHEMA = "https://opencode.ai/config.json";
const INSTRUCTIONS_KEY = "instructions";
const LOADER_KIND = "runtime loader";
const POINTER_OPEN = "<!-- orly:begin -->";
const POINTER_CLOSE = "<!-- orly:end -->";
const NEWLINE = "\n";
const JSON_INDENT = 2;

export type Layout = { orlyFile: string; pointerHost?: string };
export type LoaderResult = { written: string[]; skipped: string[] };

// What one loader destination came to. WRITTEN — orly created or refreshed it.
// CURRENT — already exactly right, by orly's hand or by someone else's wiring.
// THEIRS — the repository answered this question itself; leave it alone.
const WRITTEN = "written";
const CURRENT = "current";
const THEIRS = "theirs";
type Verdict = typeof WRITTEN | typeof CURRENT | typeof THEIRS;

// Every destination orly aims at a file it does not own, with the kind name
// the refusal will carry. Exported so the install can guard them in its
// up-front pass: a committed symlink escaping the repository must be refused
// before anything is staged, not discovered at the write.
export function loaderTargets(layout: Layout): Array<[string, string]> {
  const targets: Array<[string, string]> = [[CLAUDE_FILENAME, LOADER_KIND], [OPENCODE_FILENAME, LOADER_KIND]];
  if (layout.pointerHost) targets.unshift([layout.pointerHost, POINTER_HOST_KIND]);
  return targets;
}

// Run after the managed files land, so a repository whose install refused for
// any other reason never carries a loader pointing at rules that were not
// written.
export async function installLoaders(targetRoot: string, layout: Layout): Promise<LoaderResult> {
  const written: string[] = [];
  const skipped: string[] = [];
  const record = (path: string, verdict: Verdict) => (verdict === WRITTEN ? written : skipped).push(path);

  // The host is what a loader imports: the repository's own file, which the
  // pointer block chains onward to orly's. Importing orly's file directly
  // would deliver the harness and drop the repository's own rules, which the
  // block itself says outrank it.
  const host = layout.pointerHost ?? layout.orlyFile;
  if (layout.pointerHost) record(layout.pointerHost, await upsertPointer(targetRoot, layout.pointerHost, layout.orlyFile));
  record(CLAUDE_FILENAME, await upsertClaudeLoader(targetRoot, host));
  record(OPENCODE_FILENAME, await upsertOpencodeLoader(targetRoot, [...new Set([host, layout.orlyFile])]));
  return { written, skipped };
}

// The one edit orly makes to a file it does not own. Delimited so a re-run
// replaces exactly what the last run wrote and nothing either side of it, and
// so a user who wants orly out can delete the block by sight.
//
// The bare `@<file>` line is the load-bearing half: Claude Code resolves it as
// an import, recursively, so the rules arrive with the file instead of waiting
// for an agent to follow a link. It must stay unbackticked and alone on its
// line — an import inside a code span stays literal text, which is exactly how
// this block spent its first release delivering nothing.
function pointerBlock(orlyFile: string): string {
  return [
    POINTER_OPEN,
    `**Engineering harness:** read [\`${orlyFile}\`](${orlyFile}) as well — it carries the safety rules,`,
    "the dispatch router that names which rule page to read before which edit, and the lifecycle",
    "this repository gates on. Where the two disagree, this file wins.",
    "",
    "The line below is an import, not decoration: a runtime that resolves it loads those rules",
    "with this file, and one that does not still has the link above.",
    "",
    `@${orlyFile}`,
    POINTER_CLOSE,
  ].join(NEWLINE);
}

// What a repository with no rules of its own starts with: the pointer, and a
// visible invitation to write here. Without the second line the stub reads as
// an orly artifact and nobody touches it — which is the trap the single-file
// layout had, moved one file over.
function stubHost(block: string): string {
  return [
    "# Repository rules",
    "",
    block,
    "",
    "Write this repository's own rules below. orly never edits this file",
    "outside the block above, so nothing here is lost to an `orly update`.",
  ].join(NEWLINE);
}

async function upsertPointer(targetRoot: string, host: string, orlyFile: string): Promise<Verdict> {
  // Re-checked at the write, as every other destination is: the up-front
  // refusal pass guards the plan, this guards the target that could have
  // changed underneath the run.
  assertWritableInside(targetRoot, host, POINTER_HOST_KIND);
  const path = join(targetRoot, host);
  const block = pointerBlock(orlyFile);
  // No file, or one orly generated under an older layout where it owned this
  // name. Neither holds a line the repository wrote, so both become the stub —
  // which is the migration for anything installed before the split.
  if (!existsSync(path) || (await Bun.file(path).text()).startsWith(GENERATED_BANNER)) {
    await Bun.write(path, `${stubHost(block)}\n`);
    return WRITTEN;
  }
  const current = await Bun.file(path).text();
  const open = current.indexOf(POINTER_OPEN);
  const close = current.indexOf(POINTER_CLOSE);
  if (open >= 0 && close > open) {
    const replaced = `${current.slice(0, open)}${block}${current.slice(close + POINTER_CLOSE.length)}`;
    if (replaced === current) return CURRENT;
    await Bun.write(path, replaced);
    return WRITTEN;
  }
  await Bun.write(path, `${current.replace(/\s*$/, "")}\n\n${block}\n`);
  return WRITTEN;
}

// Claude Code auto-loads CLAUDE.md and nothing else — an AGENTS.md reaches it
// only through an import or a symlink someone made by hand. Without this file
// the promise that a teammate's clone is governed with nothing installed is
// false in the runtime most of them are running.
//
// Written ONLY where the repository has none. A CLAUDE.md that already exists
// is an answer its author gave to this exact question, and the common form of
// that answer is a symlink to AGENTS.md — where a delimited edit would land in
// the host file and import it into itself. Recognising the link as delivery
// and leaving every other CLAUDE.md alone keeps one rule for both: orly writes
// this file or it does not touch it.
async function upsertClaudeLoader(targetRoot: string, host: string): Promise<Verdict> {
  assertWritableInside(targetRoot, CLAUDE_FILENAME, LOADER_KIND);
  const path = join(targetRoot, CLAUDE_FILENAME);
  const link = linkVerdict(targetRoot, path, host);
  if (link) return link;
  const content = claudeLoader(host);
  if (!existsSync(path)) {
    await Bun.write(path, content);
    return WRITTEN;
  }
  const current = await Bun.file(path).text();
  if (current === content) return CURRENT;
  // An older loader of orly's own making is orly's to refresh; anything else
  // is the repository's file and is reported, not edited.
  if (!current.startsWith(GENERATED_BANNER)) return THEIRS;
  await Bun.write(path, content);
  return WRITTEN;
}

function claudeLoader(host: string): string {
  return [
    GENERATED_BANNER,
    "> Claude Code loads this file at session start and no other, so this is where",
    `> this repository's rules get in. The import below pulls in \`${host}\`, and`,
    "> whatever that file imports in turn — orly's rules among them.",
    ">",
    "> Delete this file to opt out; orly writes it only when it is missing, and",
    "> never edits a CLAUDE.md it did not write.",
    "",
    `@${host}`,
    "",
  ].join(NEWLINE);
}

// A CLAUDE.md symlinked at the host is the other supported wiring, and it
// delivers the same bytes: the runtime reads the link and lands in the file
// the import chain starts from. Resolving both sides matters on macOS, where
// the repository itself routinely sits behind a link.
//
// Any other link is still someone's deliberate wiring, and is left alone for
// the reason the whole loader is: a write through a symlink lands in the file
// it points at, not the one orly named. Undefined = not a link, decide on
// content.
function linkVerdict(targetRoot: string, path: string, host: string): Verdict | undefined {
  try {
    if (!lstatSync(path).isSymbolicLink()) return undefined;
  } catch {
    return undefined;
  }
  try {
    return realpathSync(path) === realpathSync(join(targetRoot, host)) ? CURRENT : THEIRS;
  } catch {
    return THEIRS;
  }
}

// opencode loads nothing by default: instructions are the paths its config
// names, so a rules file it was never told about is a rules file it never
// reads. Both entries are listed because opencode has no auto-load to fall
// back on — naming only orly's half would deliver the harness in this runtime
// and the repository's own rules in every other one.
//
// An existing config is edited by adding what is missing and nothing else. A
// config orly cannot parse is left exactly as it is: rewriting a file whose
// shape we do not understand is how an install eats someone's settings.
async function upsertOpencodeLoader(targetRoot: string, entries: string[]): Promise<Verdict> {
  assertWritableInside(targetRoot, OPENCODE_FILENAME, LOADER_KIND);
  const path = join(targetRoot, OPENCODE_FILENAME);
  if (!existsSync(path)) {
    await Bun.write(path, serialise({ $schema: OPENCODE_SCHEMA, [INSTRUCTIONS_KEY]: entries }));
    return WRITTEN;
  }
  let config: unknown;
  try {
    config = JSON.parse(await Bun.file(path).text());
  } catch {
    return THEIRS;
  }
  if (!isObject(config)) return THEIRS;
  const listed = Array.isArray(config[INSTRUCTIONS_KEY]) ? config[INSTRUCTIONS_KEY].map(String) : [];
  const missing = entries.filter((entry) => !listed.includes(entry));
  if (missing.length === 0) return CURRENT;
  await Bun.write(path, serialise({ ...config, [INSTRUCTIONS_KEY]: [...listed, ...missing] }));
  return WRITTEN;
}

function serialise(config: object): string {
  return `${JSON.stringify(config, undefined, JSON_INDENT)}\n`;
}
